package br.com.pulsar.hemocentro.entities.enums;

public enum RegionalHemocentro {

	PRESIDENTE_PRUDENTE,
	ARACATUBA,
	SAO_JOSE_DO_RIO_PRETO,
	RIBEIRAO_PRETO,
	ARARAQUARA,
	BAURU,
	MARILIA,
	ASSIS,
	CAMPINAS,
	PIRACICABA,
	ITAPETININGA,
	GRANDE_SAO_PAULO,
	SAO_PAULO_CAPITAL,
	LITORAL_SUL_PAULISTA,
	VALE_DO_PARAIBA_PAULISTA
	
}
